// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Main_BG;
void ui_event_TempArc( lv_event_t * e);
extern lv_obj_t *ui_TempArc;
void ui_event_VoltageArc( lv_event_t * e);
extern lv_obj_t *ui_VoltageArc;
extern lv_obj_t *ui_Top_Overlay;
extern lv_obj_t *ui_Celcius_Unit;
extern lv_obj_t *ui_nerdtronics;
extern lv_obj_t *ui_Voltage_Unit;
extern lv_obj_t *ui_Battery_Logo;
extern lv_obj_t *ui_Temp_Logo;
extern lv_obj_t *ui_Temp_Value;
extern lv_obj_t *ui_Voltage_Value;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_main_frame_png);   // assets/Main frame.png
LV_IMG_DECLARE( ui_img_gauge_png);   // assets/Gauge.png
LV_IMG_DECLARE( ui_img_top_body_png);   // assets/Top Body.png
LV_IMG_DECLARE( ui_img_temp_unit_png);   // assets/Temp Unit.png
LV_IMG_DECLARE( ui_img_nerdtronics_png);   // assets/nerdtronics.png
LV_IMG_DECLARE( ui_img_voltage_unit_png);   // assets/Voltage Unit.png
LV_IMG_DECLARE( ui_img_battery_logo_png);   // assets/Battery Logo.png
LV_IMG_DECLARE( ui_img_temp_logo_png);   // assets/Temp Logo.png


LV_FONT_DECLARE( ui_font_Nico_Moji_24);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
