// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: sqls files

#ifndef _SQLS_FILES_UI_H
#define _SQLS_FILES_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void seamlessground_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Gauge;
extern lv_obj_t *ui_Fuel_Tank;
extern lv_obj_t *ui_FUEL;
extern lv_obj_t *ui_Ground;
extern lv_obj_t *ui_Motorbike;
extern lv_obj_t *ui_Charging_OFF;
extern lv_obj_t *ui_Charing_ON;
extern lv_obj_t *ui_fuelLevelValue;
extern lv_obj_t *ui_batteryLevelBarValue;
extern lv_obj_t *ui_batteryLevelValue;
extern lv_obj_t *ui_Remaining;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_remainingValue;
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_ui_gauge_png);   // assets/UI/Gauge.png
LV_IMG_DECLARE( ui_img_ui_fuel_tank_png);   // assets/UI/Fuel Tank.png
LV_IMG_DECLARE( ui_img_ui_ground_png);   // assets/UI/Ground.png
LV_IMG_DECLARE( ui_img_ui_motorbike_png);   // assets/UI/Motorbike.png
LV_IMG_DECLARE( ui_img_ui_charging_charging_off_png);   // assets/UI/Charging/Charging Off.png
LV_IMG_DECLARE( ui_img_ui_charging_charging_on_png);   // assets/UI/Charging/Charging On.png
LV_IMG_DECLARE( ui_img_ui_lines_png);   // assets/UI/Lines.png


LV_FONT_DECLARE( ui_font_Font_14);
LV_FONT_DECLARE( ui_font_Font_16);
LV_FONT_DECLARE( ui_font_Font_18);
LV_FONT_DECLARE( ui_font_Font_24);
LV_FONT_DECLARE( ui_font_Font_22);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
