// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Main_BG = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Main_BG, &ui_img_main_frame_png);
lv_obj_set_width( ui_Main_BG, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Main_BG, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Main_BG, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Main_BG, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Main_BG, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Main_BG,260);

ui_TempArc = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_TempArc, 243);
lv_obj_set_height( ui_TempArc, 243);
lv_obj_set_align( ui_TempArc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_TempArc, 23);
lv_arc_set_bg_angles(ui_TempArc,0,180);
lv_obj_set_style_arc_color(ui_TempArc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TempArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_TempArc, lv_color_hex(0xFAA916), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TempArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_TempArc, 25, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_TempArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_TempArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_VoltageArc = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_VoltageArc, 243);
lv_obj_set_height( ui_VoltageArc, 243);
lv_obj_set_align( ui_VoltageArc, LV_ALIGN_CENTER );
lv_arc_set_range(ui_VoltageArc, 0,25);
lv_arc_set_value(ui_VoltageArc, 50);
lv_arc_set_bg_angles(ui_VoltageArc,180,0);
lv_obj_set_style_arc_color(ui_VoltageArc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_VoltageArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_VoltageArc, lv_color_hex(0xB95050), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_VoltageArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_VoltageArc, 25, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_VoltageArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_VoltageArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_VoltageArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Top_Overlay = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Top_Overlay, &ui_img_top_body_png);
lv_obj_set_width( ui_Top_Overlay, LV_SIZE_CONTENT);  /// 240
lv_obj_set_height( ui_Top_Overlay, LV_SIZE_CONTENT);   /// 195
lv_obj_set_align( ui_Top_Overlay, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Top_Overlay, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Top_Overlay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Celcius_Unit = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Celcius_Unit, &ui_img_temp_unit_png);
lv_obj_set_width( ui_Celcius_Unit, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Celcius_Unit, LV_SIZE_CONTENT);   /// 24
lv_obj_set_x( ui_Celcius_Unit, 32 );
lv_obj_set_y( ui_Celcius_Unit, 32 );
lv_obj_set_align( ui_Celcius_Unit, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Celcius_Unit, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Celcius_Unit, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Celcius_Unit,200);

ui_nerdtronics = lv_img_create(ui_Screen1);
lv_img_set_src(ui_nerdtronics, &ui_img_nerdtronics_png);
lv_obj_set_width( ui_nerdtronics, LV_SIZE_CONTENT);  /// 105
lv_obj_set_height( ui_nerdtronics, LV_SIZE_CONTENT);   /// 9
lv_obj_set_align( ui_nerdtronics, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_nerdtronics, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_nerdtronics, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Voltage_Unit = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Voltage_Unit, &ui_img_voltage_unit_png);
lv_obj_set_width( ui_Voltage_Unit, LV_SIZE_CONTENT);  /// 23
lv_obj_set_height( ui_Voltage_Unit, LV_SIZE_CONTENT);   /// 21
lv_obj_set_x( ui_Voltage_Unit, 32 );
lv_obj_set_y( ui_Voltage_Unit, -32 );
lv_obj_set_align( ui_Voltage_Unit, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Voltage_Unit, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Voltage_Unit, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Voltage_Unit,200);

ui_Battery_Logo = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Battery_Logo, &ui_img_battery_logo_png);
lv_obj_set_width( ui_Battery_Logo, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_Battery_Logo, LV_SIZE_CONTENT);   /// 14
lv_obj_set_x( ui_Battery_Logo, 0 );
lv_obj_set_y( ui_Battery_Logo, -67 );
lv_obj_set_align( ui_Battery_Logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Battery_Logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Battery_Logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Battery_Logo,200);

ui_Temp_Logo = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Temp_Logo, &ui_img_temp_logo_png);
lv_obj_set_width( ui_Temp_Logo, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_Temp_Logo, LV_SIZE_CONTENT);   /// 36
lv_obj_set_x( ui_Temp_Logo, 0 );
lv_obj_set_y( ui_Temp_Logo, 67 );
lv_obj_set_align( ui_Temp_Logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Temp_Logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Temp_Logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Temp_Logo,175);

ui_Temp_Value = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Temp_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temp_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temp_Value, -10 );
lv_obj_set_y( ui_Temp_Value, 32 );
lv_obj_set_align( ui_Temp_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temp_Value,"28");
lv_obj_set_style_text_color(ui_Temp_Value, lv_color_hex(0x6D676E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Temp_Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Temp_Value, &ui_font_Nico_Moji_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Voltage_Value = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Voltage_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Voltage_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Voltage_Value, -10 );
lv_obj_set_y( ui_Voltage_Value, -32 );
lv_obj_set_align( ui_Voltage_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Voltage_Value,"12");
lv_obj_set_style_text_color(ui_Voltage_Value, lv_color_hex(0x6D676E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Voltage_Value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Voltage_Value, &ui_font_Nico_Moji_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_TempArc, ui_event_TempArc, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_VoltageArc, ui_event_VoltageArc, LV_EVENT_ALL, NULL);

}
