// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: sqls files

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Gauge = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Gauge, &ui_img_ui_gauge_png);
lv_obj_set_width( ui_Gauge, LV_SIZE_CONTENT);  /// 564
lv_obj_set_height( ui_Gauge, LV_SIZE_CONTENT);   /// 340
lv_obj_set_x( ui_Gauge, 0 );
lv_obj_set_y( ui_Gauge, -37 );
lv_obj_set_align( ui_Gauge, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Gauge, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Gauge, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Gauge,85);

ui_Fuel_Tank = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Fuel_Tank, &ui_img_ui_fuel_tank_png);
lv_obj_set_width( ui_Fuel_Tank, LV_SIZE_CONTENT);  /// 69
lv_obj_set_height( ui_Fuel_Tank, LV_SIZE_CONTENT);   /// 84
lv_obj_set_x( ui_Fuel_Tank, 0 );
lv_obj_set_y( ui_Fuel_Tank, -35 );
lv_obj_set_align( ui_Fuel_Tank, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Fuel_Tank, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Fuel_Tank, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Fuel_Tank,110);

ui_FUEL = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_FUEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FUEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FUEL, 0 );
lv_obj_set_y( ui_FUEL, -3 );
lv_obj_set_align( ui_FUEL, LV_ALIGN_CENTER );
lv_label_set_text(ui_FUEL,"FUEL");
lv_obj_set_style_text_font(ui_FUEL, &ui_font_Font_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Ground = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Ground, &ui_img_ui_ground_png);
lv_obj_set_width( ui_Ground, LV_SIZE_CONTENT);  /// 1577
lv_obj_set_height( ui_Ground, LV_SIZE_CONTENT);   /// 79
lv_obj_set_x( ui_Ground, 180 );
lv_obj_set_y( ui_Ground, 111 );
lv_obj_set_align( ui_Ground, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Ground, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Ground, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Ground,85);

ui_Motorbike = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Motorbike, &ui_img_ui_motorbike_png);
lv_obj_set_width( ui_Motorbike, LV_SIZE_CONTENT);  /// 118
lv_obj_set_height( ui_Motorbike, LV_SIZE_CONTENT);   /// 118
lv_obj_set_x( ui_Motorbike, -5 );
lv_obj_set_y( ui_Motorbike, 82 );
lv_obj_set_align( ui_Motorbike, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Motorbike, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Motorbike, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Motorbike,85);

ui_Charging_OFF = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Charging_OFF, &ui_img_ui_charging_charging_off_png);
lv_obj_set_width( ui_Charging_OFF, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_Charging_OFF, LV_SIZE_CONTENT);   /// 65
lv_obj_set_x( ui_Charging_OFF, 45 );
lv_obj_set_y( ui_Charging_OFF, 79 );
lv_obj_set_align( ui_Charging_OFF, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Charging_OFF, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Charging_OFF, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Charging_OFF,140);

ui_Charing_ON = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Charing_ON, &ui_img_ui_charging_charging_on_png);
lv_obj_set_width( ui_Charing_ON, LV_SIZE_CONTENT);  /// 25
lv_obj_set_height( ui_Charing_ON, LV_SIZE_CONTENT);   /// 65
lv_obj_set_x( ui_Charing_ON, 45 );
lv_obj_set_y( ui_Charing_ON, 79 );
lv_obj_set_align( ui_Charing_ON, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Charing_ON, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Charing_ON, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Charing_ON,140);

ui_fuelLevelValue = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_fuelLevelValue, 242);
lv_obj_set_height( ui_fuelLevelValue, 242);
lv_obj_set_align( ui_fuelLevelValue, LV_ALIGN_CENTER );
lv_arc_set_value(ui_fuelLevelValue, 0);
lv_arc_set_bg_angles(ui_fuelLevelValue,180,0);
lv_obj_set_style_arc_color(ui_fuelLevelValue, lv_color_hex(0x8A887F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_fuelLevelValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_fuelLevelValue, 23, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_fuelLevelValue, true, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_fuelLevelValue, lv_color_hex(0xFFBD00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_fuelLevelValue, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_fuelLevelValue, 23, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_fuelLevelValue, true, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_fuelLevelValue, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_fuelLevelValue, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_batteryLevelBarValue = lv_bar_create(ui_Screen1);
lv_bar_set_mode(ui_batteryLevelBarValue, LV_BAR_MODE_RANGE);
lv_bar_set_value(ui_batteryLevelBarValue,45,LV_ANIM_OFF);
lv_bar_set_start_value(ui_batteryLevelBarValue, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_batteryLevelBarValue, 26);
lv_obj_set_height( ui_batteryLevelBarValue, 10);
lv_obj_set_x( ui_batteryLevelBarValue, -55 );
lv_obj_set_y( ui_batteryLevelBarValue, 71 );
lv_obj_set_align( ui_batteryLevelBarValue, LV_ALIGN_CENTER );
lv_obj_set_style_outline_color(ui_batteryLevelBarValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_batteryLevelBarValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_batteryLevelBarValue, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_batteryLevelBarValue, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_batteryLevelBarValue, lv_color_hex(0x22FF03), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batteryLevelBarValue, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_batteryLevelValue = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_batteryLevelValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryLevelValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_batteryLevelValue, -54 );
lv_obj_set_y( ui_batteryLevelValue, 87 );
lv_obj_set_align( ui_batteryLevelValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryLevelValue,"100");
lv_obj_set_style_text_color(ui_batteryLevelValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_batteryLevelValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batteryLevelValue, &ui_font_Font_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Remaining = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Remaining, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Remaining, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Remaining, -52 );
lv_obj_set_y( ui_Remaining, 35 );
lv_obj_set_align( ui_Remaining, LV_ALIGN_CENTER );
lv_label_set_text(ui_Remaining,"REMAINING");
lv_obj_set_style_text_letter_space(ui_Remaining, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Remaining, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Remaining, &ui_font_Font_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_ui_lines_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 590
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 145
lv_obj_set_x( ui_Image1, -3 );
lv_obj_set_y( ui_Image1, 34 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image1,90);

ui_remainingValue = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_remainingValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_remainingValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_remainingValue, 50 );
lv_obj_set_y( ui_remainingValue, 35 );
lv_obj_set_align( ui_remainingValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_remainingValue,"100");
lv_obj_set_style_text_color(ui_remainingValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_remainingValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_remainingValue, &ui_font_Font_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
